Company.create!([
  {name: "ボストンコンサルティンググループ", logoURL: "http://www.sarasijam.com/images/bcg-logo.gif"},
  {name: "リクルートライフスタイル", logoURL: "https://s3-ap-northeast-1.amazonaws.com/in-fra/company/main_img/44ee5c45d822d94923637dabc2a86c04_production"},
  {name: "レバレジーズ", logoURL: "http://leverages.up.seesaa.net/image/lv_logo%28LeveragesE381AEE381BF%29.jpg"},
  {name: "DeNA", logoURL: "https://anywher.net/wp-content/uploads/2014/11/logo-color_DeNA.jpg"},
  {name: "LITALICO", logoURL: "http://www.zaikei.co.jp/files/press/201411181620031dg1.jpg"},
  {name: "ワークスアプリケーションズ", logoURL: "http://jeek.s3.amazonaws.com/corporation/img/654/corp_654.jpg"},
  {name: "野村総合研究所", logoURL: "https://s3-ap-northeast-1.amazonaws.com/lionlogo/nri.png"},
  {name: "ＩＨＩ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アイカ工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アイシン精機",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アインファーマシーズ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＡＯＫＩホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "あおぞら銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アコム",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "旭化成",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "旭硝子",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アサヒグループホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アサヒホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アシックス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "味の素",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アステラス製薬",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アルプス電気",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アルフレッサホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "安藤・間",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アンリツ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "イーグル工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "eBASE",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "飯田グループホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "イオン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "イオンディライト",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "イオンフィナンシャルサービス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "イオンモール",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "いすゞ自動車",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "イズミ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "伊藤園",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "伊藤忠商事",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "伊藤忠テクノソリューションズ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "伊予銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "岩谷産業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ウエルシアホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "宇部興産",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エーザイ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エービーシー・マート",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エア・ウォーター",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＡＮＡホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エイチ・アイ・エス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エイベックス・グループ・ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エクセディ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＳＭＣ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "SCSK",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＳＢＩホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＮＯＫ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＮＴＴデータ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＮＴＴドコモ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エヌ・ティ・ティ都市開発",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "荏原製作所",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＭＳ＆ＡＤインシュアランスグループホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エムスリー",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エンプラス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "オーエスジー",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "オービック",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "王子ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大阪ガス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大塚商会",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大塚ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大林組",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "岡三証券グループ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "沖電気工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "小田急電鉄",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "小野薬品工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "オムロン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "オリエンタルランド",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "オリックス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "オリンパス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "花王",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "カカクコム",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "科研製薬",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "カシオ計算機",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "鹿島建設",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "カナモト",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "兼松",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "カブドットコム証券",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "カルソニックカンセイ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "カルビー",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "川崎重工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "関西ペイント",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ガンホー・オンライン・エンターテイメント",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "キーエンス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "キッコーマン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "キヤノン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "キューピー",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "キョーリン製薬ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "京セラ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "協和エクシオ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "協和発酵キリン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "キリンホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "近鉄エクスプレス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "近鉄グル－プホ－ルディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "クックパッド",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "クボタ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "クラレ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "グリー",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "クレディセゾン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "群馬銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ケーズホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "京王電鉄",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "京成電鉄",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＫＤＤＩ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "京阪電気鉄道",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "京葉銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ゲオホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "コーセー",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "興銀リース",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "神戸製鋼所",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "小糸製作所",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "国際石油開発帝石",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "コスモス薬品",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "コニカミノルタ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "小林製薬",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "小松製作所",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "コムシスホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "コンコルディア・ＦＧ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "サイバーエージェント",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "沢井製薬",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "三協立山",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "参天製薬",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "サンドラッグ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "サンリオ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "三和ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＧＭＯインターネット",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＪＳＲ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ＪＦＥホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ジェイテクト",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "Ｊ．フロントリテイリング",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "塩野義製薬",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "静岡銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "シスメックス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "資生堂",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "シップヘルスケアホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "シマノ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "しまむら",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "清水建設",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ジャフコ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "十六銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "常陽銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "昭和シェル石油",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "信越化学工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "新生銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "新日鐵住金",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "スギホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "スズキ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "スターツコーポレーション",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "スタートトゥデイ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "スタンレー電気",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友化学工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友金属鉱山（株）",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友ゴム工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友重機械工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友商事",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友電気工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友林業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友不動産",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "住友不動産販売",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "スルガ銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "セイコーエプソン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "セイコーホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "セガサミーホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "積水化学工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "積水ハウス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "セコム",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "セブン＆アイ・ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "セブン銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "セリア",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "綜合警備保障",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "双日",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "相鉄ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ソニーフィナンシャルホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ソフトバンクグループ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "損保ジャパン日本興亜ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "第一興商",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "第一三共",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "第一生命保険",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大京",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ダイキン工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ダイハツ工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大王製紙",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大正製薬ホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大成建設",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ダイセル",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大東建託",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "太平洋セメント",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大陽日酸",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大和証券グループ本社",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "大和ハウス工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "高島屋",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "タカラレーベン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "武田薬品工業",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "タダノ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "田辺三菱製薬",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "千葉銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "中外製薬",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "中国銀行",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "千代田化工建設",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "椿本チエイン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ツムラ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ツルハホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "Ｔ＆Ｄホールディングス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "インテリジェンス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "トライアンフ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ディスコ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ヒューマネージ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "マイナビ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "シンカ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ワークス・ジャパン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ワークスアプリケーションズ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "イグナイトアイ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エン・ジャパン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "カオナビ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "日本データビジョン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アル―",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "エイチアールワン",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "セゾン情報システムズ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アマノ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "シーエーシー",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "キャリアマート",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "日本エス・エイチ・エル",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "電通国際情報サービス（ISID）",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ペイロール",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "鈴与シンワート",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "キャリアデザインセンター",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "リクルートエージェント",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ネオキャリア",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ガイアックス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "シルクロード",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "富士通ラーニングメディア",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アクセンチュア",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アチーブメント",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "さくら情報システム",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ラクラス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "パソナ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ディリゴ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ベクトル",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "HRソリューションズ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "サクセスファクターズ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "プロシーズ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "東京海上日動キャリアサービス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "サイバックス",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "ビジネスネットコーポレーション",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "アイエンター",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "マングローブ",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  },
  {name: "リンクアソシア",  logoURL: "http://www.medic-one.org/assets/frontend/images/no-banner.jpg",  }  
])
Interest.create!([
  {user_id: 1, company_id: 1, status: "最終面接", date: "2016-08-09", score: 9},
  {user_id: 1, company_id: 2, status: "1次選考中", date: "2016-07-17", score: 7},
  {user_id: 1, company_id: 3, status: "情報収集中", date: "2016-08-09", score: 7},
  {user_id: 1, company_id: 5, status: "2次選考", date: "2016-07-19", score: 7},
  {user_id: 1, company_id: 6, status: "情報収集中", date: "2016-07-24", score: 5},
  {user_id: 1, company_id: 7, status: "最終面接", date: "2016-07-28", score: 6},
  {user_id: 1, company_id: 4, status: "情報収集中", date: "2016-07-07", score: 0}
])
InterestMemo.create!([
  {interest_id: 1, date: "2016-07-05", memo: "人事部　佐藤さんと面談を行った。"},
  {interest_id: 1, date: "2016-06-12", memo: "営業部　山田さんと面談を行った。実際に営業部の業務を伺う。"},
  {interest_id: 1, date: "2016-07-07", memo: "役員面談　鈴木様　\r\n将来的に自分が話したい展望を語る。\r\n 事業の方向性がスケールの方法に問題意識を持っていた。"},
  {interest_id: 1, date: "2016-07-07", memo: "内定懇親会\r\n同期の山田さん、藤城さん、松田さんと意気投合する。\r\nおそらく配属先は異なるが、今後も良い仲間関係を保っていきたい。"},
  {interest_id: 2, date: "2016-07-07", memo: "営業担当　山田裕太さん\r\n入社における軸などを聞いた。\r\n自分の在り方と少し似ている物を感じ、\r\n文化適合度の評価を上げた。"},
  {interest_id: 2, date: "2016-07-08", memo: "2次選考のために下記の点について考える事とする。\r\n・入社したら何をしたいか\r\n・入社する前に何をしたいか\r\n・どんな環境で働きたいか"}
])
User.create!([
  {name: "tomoki", email: "tomoki@gmail.com", tel: "111-382-1906", password_digest: "$2a$10$COlm/x/.kHIfwuWbc089DOgmfdFP721liA0zS5vklplDmyNY.YA9a", kind: "user"},
  {name: "tomoki2", email: "tomoki2@gmail.com", tel: "111-382-1907", password_digest: "$2a$10$oUGUMOTomEHapNT4eEKbVOkiWEUGaF1srHxCGXVBRlLLEzHcNQwkC", kind: "user"}
])
